### ISSUE TITLE
wrong when i update plugin symless 

### ISSUE THREAD

**Issue by zhefox** [rand-tech/ida9rewriter#1]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\Scripts\ida9rewriter.exe\__main__.py", line 7, in <module>
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 69, in cli
    run(args.source, args.dryrun, args.recursive)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 50, in run
    file, result = future.result()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
AttributeError: 'Attribute' object has no attribute 'startswith'

**Comment by zhefox** [comment]
https://github.com/thalium/symless
this plugin

**Comment by zhefox** [comment]
Processing files:  38%|████████████████████████                                       | 8/21 [00:01<00:02,  5.27file/s]
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 23, in process_file
    new_source = bump_ida(source_code)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 16, in bump_ida
    source_code = pass_(source_code)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\codemods\replace_simple.py", line 183, in bump_ida_simple
    modified_module = module.visit(transformer)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\module.py", line 89, in visit
    result = super(Module, self).visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\module.py", line 74, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 1814, in _visit_and_replace_children
    body=visit_required(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 698, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 616, in _visit_and_replace_children
    body=visit_required(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 698, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 616, in _visit_and_replace_children
    body=visit_required(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 698, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 443, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 177, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 159, in visit_iterable
    new_child = child.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 227, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\statement.py", line 348, in _visit_and_replace_children
    value=visit_required(self, "value", self.value, visitor),
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_nodes\base.py", line 236, in visit
    leave_result = visitor.on_leave(self, with_updated_children)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\matchers\_visitors.py", line 515, in on_leave
    retval = CSTTransformer.on_leave(self, original_node, updated_node)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\libcst\_visitors.py", line 71, in on_leave
    updated_node = leave_func(original_node, updated_node)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\codemods\replace_simple.py", line 131, in leave_Call
    if full_name in REPLACEMENTS or self._check_glob_imports(full_name):
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\codemods\replace_simple.py", line 144, in _check_glob_imports
    if full_name.startswith(glob_import):
AttributeError: 'Attribute' object has no attribute 'startswith'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\Scripts\ida9rewriter.exe\__main__.py", line 7, in <module>
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 69, in cli
    run(args.source, args.dryrun, args.recursive)
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ida9rewriter\cli.py", line 50, in run
    file, result = future.result()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
AttributeError: 'Attribute' object has no attribute 'startswith'

**Comment by rand-tech** [comment]
Hi, thanks for reporting it. 

I can fix the problem, but this tool is aimed for 8.* to 9.0 and not 7.* to 9.0.  Do you have a working 8.* plugin?

**Comment by zhefox** [comment]
It works on version 8.1，Maybe the APIs of 8.1 and 8.4 have also changed.Looking forward to it being updated uniformly, this is creative

**Comment by rand-tech** [comment]
> Maybe the APIs of 8.1 and 8.4 have also changed

I think that is the case 🤦.

I will work on the error in the next 1 week. (I am currently busy and can't work on it right now.)
